In [2]:
import osmnx as ox
import geopandas as gpd
import pandas as pd
import numpy as np

In [7]:
%%time
cf = '["highway"~"motorway|motorway_link"]'
G1 = ox.graph_from_place(
    [
        "Chiba, Japan",
    ],
    simplify=True,
    custom_filter=cf,
)
G2 = ox.graph_from_place(
    [
        "Osaka, Japan",
    ],
    simplify=True,
    custom_filter=cf,
)

CPU times: user 10.8 s, sys: 115 ms, total: 10.9 s
Wall time: 39.2 s

In [8]:
nodes1, edges1 = ox.graph_to_gdfs(G1)
nodes2, edges2 = ox.graph_to_gdfs(G2)

nodes = pd.concat([nodes1, nodes2])
edges = pd.concat([edges1, edges2])

display(nodes)
display(edges)

,y,x,osmid,ref,highway,geometry
241206273,35.559685,140.139009,241206273,NaN,NaN,POINT (140.13901 35.55968)
241206275,35.559811,140.138868,241206275,12,motorway_junction,POINT (140.13887 35.55981)
626557444,35.608204,140.152424,626557444,10,motorway_junction,POINT (140.15242 35.60820)
1830268934,35.599377,140.161048,1830268934,NaN,NaN,POINT (140.16105 35.59938)
2192202762,35.590497,140.145987,2192202762,NaN,NaN,POINT (140.14599 35.59050)
...,...,...,...,...,...,...
1831049210,34.582065,135.462500,1831049210,NaN,NaN,POINT (135.46250 34.58206)
1604323324,34.451906,135.354746,1604323324,4-19,motorway_junction,POINT (135.35475 34.45191)
1604323325,34.448722,135.352183,1604323325,NaN,NaN,POINT (135.35218 34.44872)
294111230,34.807322,135.429878,294111230,NaN,NaN,POINT (135.42988 34.80732)
5409269759,34.598663,135.473999,5409269759,NaN,NaN,POINT (135.47400 34.59866)

,osmid,oneway,lanes,highway,length,geometry,ref,name,maxspeed,bridge,tunnel,u,v,key,access
0,155792075,True,1,motorway_link,242.509,"LINESTRING (140.13887 35.55981, 140.13881 35.5...",NaN,NaN,NaN,NaN,NaN,241206275,1681546550,0,NaN
1,"[156577509, 156577254, 156577512, 156179209, 3...",True,2,motorway,1488.530,"LINESTRING (140.13887 35.55981, 140.13859 35.5...",E14,"[館山自動車道, 京葉道路]",80,"[yes, viaduct]",NaN,241206275,1684609904,0,NaN
2,"[144560863, 172086519, 172086517, 49334815]",True,"[2, 1]",motorway_link,1472.523,"LINESTRING (140.15242 35.60820, 140.15244 35.6...",NaN,NaN,NaN,yes,NaN,626557444,1830268934,0,NaN
3,144560843,True,2,motorway,866.437,"LINESTRING (140.15242 35.60820, 140.15198 35.6...",E14,京葉道路,80,yes,NaN,626557444,4889381514,0,NaN
4,303755029,True,2,motorway,1723.765,"LINESTRING (140.16105 35.59938, 140.16205 35.5...",E82,千葉東金道路,80,NaN,NaN,1830268934,3815800588,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1069,"[131220397, 128750423]",True,1,motorway_link,273.706,"LINESTRING (135.42101 34.66848, 135.42040 34.6...",5,阪神高速5号湾岸線,NaN,yes,NaN,1421916150,1421916271,0,NaN
1070,"[32561123, 556030452, 172170215]",True,1,motorway_link,285.895,"LINESTRING (135.46250 34.58206, 135.46244 34.5...",NaN,大浜入口,NaN,yes,NaN,1831049210,361895064,0,NaN
1071,33434021,True,2,motorway,1574.021,"LINESTRING (135.35475 34.45191, 135.35347 34.4...",4,阪神高速4号湾岸線,80,yes,NaN,1604323324,1871656093,0,NaN
1072,147221248,True,1,motorway_link,429.204,"LINESTRING (135.35475 34.45191, 135.35463 34.4...",NaN,貝塚出口,NaN,yes,NaN,1604323324,1604323325,0,NaN
1073,"[473990632, 560926039, 779025735]",True,2,motorway,1223.908,"LINESTRING (135.47400 34.59866, 135.47216 34.5...",6,阪神高速6号大和川線,80,yes,yes,5409269759,4680168881,0,NaN

In [11]:
edges2 = edges[['highway', 'length', 'geometry']].copy()

In [12]:
edges2['highway'] = edges2['highway'].map(lambda x: None if type(x) == list else x)
edges2 = edges2.dropna()
edges2

,highway,length,geometry
0,motorway_link,242.509,"LINESTRING (140.13887 35.55981, 140.13881 35.5..."
1,motorway,1488.530,"LINESTRING (140.13887 35.55981, 140.13859 35.5..."
2,motorway_link,1472.523,"LINESTRING (140.15242 35.60820, 140.15244 35.6..."
3,motorway,866.437,"LINESTRING (140.15242 35.60820, 140.15198 35.6..."
4,motorway,1723.765,"LINESTRING (140.16105 35.59938, 140.16205 35.5..."
...,...,...,...
1069,motorway_link,273.706,"LINESTRING (135.42101 34.66848, 135.42040 34.6..."
1070,motorway_link,285.895,"LINESTRING (135.46250 34.58206, 135.46244 34.5..."
1071,motorway,1574.021,"LINESTRING (135.35475 34.45191, 135.35347 34.4..."
1072,motorway_link,429.204,"LINESTRING (135.35475 34.45191, 135.35463 34.4..."
1073,motorway,1223.908,"LINESTRING (135.47400 34.59866, 135.47216 34.5..."

In [14]:
edges2.to_file("edges_highway/edges.shp")

In [15]:
nodes[['highway', 'geometry']].to_file("nodes_highway/nodes.shp")

In [16]:
! tar czvf edges_highway.tar.gz edges_highway

edges_highway/
edges_highway/edges.prj
edges_highway/edges.dbf
edges_highway/edges.shp
edges_highway/edges.shx
edges_highway/edges.cpg

In [17]:
! tar czvf nodes_highway.tar.gz nodes_highway

nodes_highway/
nodes_highway/nodes.prj
nodes_highway/nodes.shp
nodes_highway/nodes.shx
nodes_highway/nodes.dbf
nodes_highway/nodes.cpg